### ISSUE TITLE
Method drowpdown in the class editor 

### ISSUE THREAD

**Issue by Yivan** [ThomasKeil/pimcore-plugin-DynamicDropdown#19] opened 2016-11-22 00:59 UTC
In the class editor, the method dropdown doen't work on the first try.
It is needed to choose one time more the Allowed class and after this the Method dropdown show the method choices.

See screenshot please:
![3](https://cloud.githubusercontent.com/assets/9025839/20506863/51786018-b057-11e6-8d53-b966899f96e1.png)

**Comment by ThomasKeil** [comment] 2016-11-22 20:48
I changed the handling of store reloading of the cascading comboboxes and can't reproduce the behavior anymore.
Can you please confirm?

**Comment by Yivan** [comment] 2016-11-23 13:11
It works great now. You can close this issue.
Thanks a lot for your fast answer!

**Comment by ThomasKeil** [comment] 2016-11-23 13:16
Great, thanks for your feedback!

**Comment by Yivan** [comment] 2016-11-25 00:35
@ThomasKeil I just discover that the problem always occurs in the case you just create the field in the class editor.
The issue should be re-opened.

To reproduce it, just create a new field of type Dynamic Dropdown, choose an "Allowed class" and after try choosing a "Method": they will just appear very fast and after disapear and leave blanck.

It tested all 4 types, and same problem occurs for all of them.

**Comment by ThomasKeil** [comment] 2016-11-27 18:16
This should be fixed now. It was kinda working in the first place, but since the combobox was set to "remote" it reloaded it's data without a needed parameter.
Setting it to "local" should've fixed that.

**Comment by Yivan** [comment] 2016-11-28 12:07
Thank you Thomas.
It works nice now, i confirm you can close the issue.

**Comment by ThomasKeil** [comment] 2016-11-28 12:08
Great, thanks for your feedback.

**Closed by ThomasKeil** 2016-11-28 12:08 UTC
Labels: bug
